[meta]
name        = "Glacial Medals"
author      = "Mattynator"
category    = "MattyPlugins"
version     = "0.1.2"

[script]
dependencies = [ "NadeoServices" ]
optional_dependencies = [ "UltimateMedalsExtended" ]